### ISSUE TITLE
Ask for confirmation before deleting things

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/acehelp#596] opened 2018-09-22 14:56 UTC
I just clicked delete article. There was no confirmation box. Anyone count click it by mistake.
No data should be allowed to be deleted without confirmation

https://monosnap.com/file/QcV1wBwpuV6dCN6rlASd9Whd7SWdjv

**Comment by neerajdotname** [comment] 2018-09-23 16:12
Duplicate of https://github.com/bigbinary/acehelp/issues/584

**Closed by neerajdotname** 2018-09-23 16:12 UTC
